version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    versioning-strategy: increase
    ignore:
      - dependency-name: "@types/node"

  - package-ecosystem: npm
    directory: "/examples/next-js"
    schedule:
      interval: weekly
    versioning-strategy: increase
    ignore:
      - dependency-name: "@types/node"

  - package-ecosystem: npm
    directory: "/packages/cms"
    schedule:
      interval: weekly
    versioning-strategy: increase
    ignore:
      - dependency-name: "@types/node"

  - package-ecosystem: npm
    directory: "/apps/website"
    schedule:
      interval: weekly
    versioning-strategy: increase
    ignore:
      - dependency-name: "@types/node"
    groups:
      tanstack:
        patterns:
          - "@tanstack/*"
