#!/usr/bin/env node
import { AUTOGENERATED_FILE_NAME } from "../data";
import { runBuild } from "./build";

async function main() {
  const [command] = process.argv.slice(2);

  switch (command) {
    case "build":
      await runBuild();
      return;
    default:
      console.error(
        command
          ? `Unknown command: ${command}`
          : `Usage: qino <command>\n\nCommands:\n  build    Validate config and write ${AUTOGENERATED_FILE_NAME}`,
      );
      process.exit(1);
  }
}

main().catch((err) => {
  const message = err instanceof Error ? err.message : String(err);
  console.error(`Error: ${message}`);
  process.exit(1);
});
