import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { z } from "zod";
import type { Config } from "./create-config";
import { LockFileSchema } from "../../schemas/lock-file";
import { AUTOGENERATED_FILE_NAME, ROOT_FOLDER_NAME } from "../../lib";

export async function loadConfig(): Promise<Config> {
  const lockPath = join(
    process.cwd(),
    ROOT_FOLDER_NAME,
    AUTOGENERATED_FILE_NAME,
  );

  let raw: string;
  try {
    raw = await readFile(lockPath, "utf8");
  } catch {
    throw new Error(
      `${AUTOGENERATED_FILE_NAME} not found at ${lockPath}. Run \`qino build\` before using collections.`,
    );
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (cause) {
    throw new Error(
      `${AUTOGENERATED_FILE_NAME} at ${lockPath} is not valid JSON.`,
      {
        cause,
      },
    );
  }

  const result = LockFileSchema.safeParse(parsed);
  if (!result.success) {
    throw new Error(
      `${AUTOGENERATED_FILE_NAME} at ${lockPath} has an invalid shape. Run \`qino build\` to regenerate it.\n${z.prettifyError(result.error)}`,
    );
  }

  return result.data.config;
}
